### ISSUE TITLE
select2 stopped working after upgrade from APEX 4.2 to APEX 5.1

### ISSUE THREAD

**Issue by alanlawlor** [nbuytaert1/apex-select2#101]
I am using Theme 25 Blue Responsive and made no attempt to switch to Universal Theme

Simply upgraded APEX from 4.2 to 5.1. select2 stopped working.

I have tried import of latest 3.0.3 version but still not working

The page item I am examining would normally have the "select2-container" class, but this is not visible in the HTML on the upgraded version. In addition Firefox show the following on JS errors : 
![image](https://user-images.githubusercontent.com/11071926/41172722-a7f70488-6b4c-11e8-8943-17a82cc5eb48.png)

**Comment by nbuytaert1** [comment]
It looks like APEX can't access the plugin static files. Did you complete all required steps to successfully upgrade APEX? This is usually the culprit of this kind of error.

Some helpful resources maybe:
http://www.inside-oracle-apex.com/apex-5-0-there-are-issues-with-the-configuration-of-the-static-files-in-your-environment/
https://community.oracle.com/thread/3774608

**Comment by alanlawlor** [comment]
Thanks, Nick 

That was the problem. We found MOS Doc ID 2004672.1 which sorted the problem
