### ISSUE TITLE
Select2 and Required - Floating issue

### ISSUE THREAD

**Issue by JacoFourie** [nbuytaert1/apex-select2#103]
Hi.

We are using Apex 18.1 and if you change the Required Template to floating the text of the label and the selected item will be stacked the one over the other. Thus you can not read the text very well.

![image](https://user-images.githubusercontent.com/17771641/43711774-1e944a88-9974-11e8-9b90-34f2c79cc30d.png)

**Comment by nbuytaert1** [comment]
Someone forked this repo and fixed the floating issue:
https://github.com/Zdro/apex-select2

Demo: https://apex.oracle.com/pls/apex/f?p=53730:1

**Comment by JacoFourie** [comment]
Mmmmm I imported that Plug-in but still have the same issue.
Thanks for the link.  The Demo works correctly but not on our side.
I imported and replaced the old one. Is there something else I need to do ?

Regards.

**Comment by nbuytaert1** [comment]
The GitHub repo includes an export file of Zdro's demo application. It's located in the _src/main_ folder. The name of the file is f2001.sql.
https://github.com/Zdro/apex-select2/tree/master/src/main

If you download and import that application, you should have a working example of the floating labels in combination with the Select2 plugin. You can then export the plugin from the demo application by going to Shared Components > Plug-ins > Export Plug-in.

**Comment by PartyPenguin** [comment]
I had to change Look And Feel Setting under Shared Components -> Component Settings -> Edit Select2 
to 'Universal Theme'
Now its working for me

**Comment by JacoFourie** [comment]
Aaa OK thanks for that. Now I see that the Width attribute is not working. If you set it to required - floating the item will span the full screen. Mmmm let me play some more with it.
