### ISSUE TITLE
SelectList2 on Apex 18.2

### ISSUE THREAD

**Issue by ericyuri** [nbuytaert1/apex-select2#107]
Hi, did you try to use selectlist2 on Apex 18.2 ? Do you known any turnaround solutions for it ?

Thank you

![image](https://user-images.githubusercontent.com/13050062/47918531-3240f500-de83-11e8-982f-8bff4d51f2af.png)
 
@maxime-tremblay @rimblas @martindsouza @nbuytaert1

**Comment by rimblas** [comment]
There must be something else at play here.  The demo app works fine http://apex.oracle.com/pls/apex/f?p=64237:20
Or maybe it's because the demo app is using jQuery Migrate

**Comment by ericyuri** [comment]
Hi @rimblas, the problem was on the ords. thank you

**Comment by JacoFourie** [comment]
OK then you should close the issue.

**Comment by Alien-nick** [comment]
Hi, @ericyuri can you help me in solving this problem by configuring ORDS? The help will be much appreciated.

**Comment by ericyuri** [comment]
@Alien-nick 
try this
`java -jar ords.war validate --database apex. java -jar ords.war static`

For debug it is convinient to edit ORDS config file defaults.xml with these strings
```
<entry key="debug.debugger">true</entry>
<entry key="debug.printDebugToScreen">true</entry>
```

Don't forget to set them false on production.
