### ISSUE TITLE
APEX 19

### ISSUE THREAD

**Issue by avhrst** [nbuytaert1/apex-select2#108]
Plugin doesn't work in APEX 19

**Comment by nbuytaert1** [comment]
The Select2 plugin demo pages on apex.oracle.com, which runs on APEX version 19.1, are still working. There might be a problem with your environment's static file configuration. Are other plugins working as expected?

More information:
http://www.inside-oracle-apex.com/apex-5-0-there-are-issues-with-the-configuration-of-the-static-files-in-your-environment/
