### ISSUE TITLE
set text if not data found

### ISSUE THREAD

**Issue by jekeam** [nbuytaert1/apex-select2#109]
Hi! How do I make it accept a random text? I. e. choose from the list, or set manually?
I need a story like in a search engine:
<img src="https://developers.google.com/search/docs/data-types/images/sitelinks01.png" />

**Comment by nbuytaert1** [comment]
Set the Select List Type setting to Tagging Support.

> When tagging support is enabled, the user can select from pre-existing options or create new options on the fly.
