### ISSUE TITLE
APEX 19.1. modal window

### ISSUE THREAD

**Issue by spock1984** [nbuytaert1/apex-select2#110]
Hi!

Plugin works great in version 19.1.
But I have a rendering problem using plugin in modal window.
It would be great if modal would resize automatically after clicking on LOV if it can't fit on page.

Please see example with 2 native LOV's and 2 select2 LOV's at:
https://apex.oracle.com/pls/apex/f?p=127537

Do you or anyone have any quick solution for this?
Thanks!

**Comment by nbuytaert1** [comment]
A modal window is an iFrame element. This means that elements inside the iFrame can't extend the borders of the iFrame. More info here: https://stackoverflow.com/questions/31081821/extend-div-outside-bounds-of-iframe

The easy solution here is to make the height of the modal window larger. Use the _Height_ setting on page level.

**Comment by spock1984** [comment]
Thanks Nick!
I know about height, just wondering is it possible.
