### ISSUE TITLE
Unable to set value to Nth value in the list

### ISSUE THREAD

**Issue by ScottHollows** [nbuytaert1/apex-select2#121]
With a regular SELECT item (not Select2) it is possible to set the value of the item to the first value in the drop list

![image](https://user-images.githubusercontent.com/4010210/72701825-9b498100-3b8b-11ea-90fc-c0e93cd39b1d.png)

There are at least three ways to do this with a regular ApEx Select item, but none of these work with Select2

1) Javascript
document.getElementById("P1234_MY_ITEM").selectedIndex = 0;

2) Javascript
document.getElementById("P1234_MY_ITEM").options[0].selected = true;

3) Javascript JQuery
$("P1234_MY_ITEM").get(0).selectedIndex = 0;
For all of these, Ive tried with and without quotes "0" but no luck

Is there a way to do this with Select2 ?

**Comment by nbuytaert1** [comment]
Your JavaScript statements are fine, but they need an extra line for Select2 to pick up the changed value. For example:

```javascript
document.getElementById("P1234_MY_ITEM").selectedIndex = 0;
$("#P1234_MY_ITEM").trigger('change');
```

**Comment by ScottHollows** [comment]
I have verified that your solution works

Thank you

Closing
