### ISSUE TITLE
Problem with Select2 in Interactive Grids for Oracle Apex 20.2

### ISSUE THREAD

**Issue by basudevsingh18** [nbuytaert1/apex-select2#125]
Hi
For a while now I had to change all my interactive grid LOVs from select2 to popup lov since apex was upgraded to 20.2
I don't know why this is happening. When I try to open a select2 list in an interactive grid, it does not open and starts to glitch regardless if it is a sql query or a plsql function body.

I would really like to start using back the select2 lov instead of the popup lov. 

Thanks in advance for your help!  @nbuytaert1

**Comment by nbuytaert1** [comment]
The Select2 plugin and Interactive Grid are not compatible. And I don't think they ever will... Sorry.

**Comment by basudevsingh18** [comment]
It was good while it lasted
