### ISSUE TITLE
Need version on APEX Download page

### ISSUE THREAD

**Issue by rimblas** [nbuytaert1/apex-select2#34]
I think the version of the plugin should be displayed close to the "Download" link on https://apex.oracle.com/pls/apex/f?p=64237:20:0:::::

From that page it's not possible to see the current version.  Maybe even the date the version was released.
:)

**Comment by nbuytaert1** [comment]
You are absolutely right. Fixing it straight away.

**Comment by nbuytaert1** [comment]
Added the plugin version and release date to the download page. Thanks for the advice, Jorge.

**Comment by rimblas** [comment]
Awesome! Looks great!
