### ISSUE TITLE
Loading Multiple Values into Select2

### ISSUE THREAD

**Issue by JoeStratton** [nbuytaert1/apex-select2#39]
The multi value select2 option works great for saving and even loading a form again when a single value is selected.

When I save multiple values into the field its store in the fomat val1:val2:val3 

My question is how do you manually load those values back into the item on page load?

Thanks!

**Comment by nbuytaert1** [comment]
Sorry for the late reply.

Loading multiple values into a Select2 page item should automatically be taken care of. Simply assign the colon separated value to the page item (e.g. 7839:7521).

**Comment by JoeStratton** [comment]
Yes I solved that :) but the max amount of select2 items on the page still seems to be limited

**Comment by nbuytaert1** [comment]
I have answered that question on apex-plugin.com:
http://www.apex-plugin.com/oracle-apex-plugins/item-plugin/select2_344.html
