### ISSUE TITLE
APEX: 5.0 Stretch Form Fields not working

### ISSUE THREAD

**Issue by martindsouza** [nbuytaert1/apex-select2#48]
When a Select 2 item is in a region who's template option `item width` = `Stretch Form Fields`, the item doesn't fill in the full space.

Screen shot below highlights this (included grid output but don't think it's relevant in this case)

![image](https://cloud.githubusercontent.com/assets/2925726/10115458/733970a0-63c5-11e5-8532-cde0f972a124.png)

**Comment by nbuytaert1** [comment]
Fixed in version 2.6.4.
The "Component Settings" section now includes a "Look and Feel" item. Select "Universal Theme" to enable better integration between Select2 items and the Universal Theme.

**Comment by martindsouza** [comment]
Just tested. Looks good. Thanks!
