### ISSUE TITLE
Plugin look

### ISSUE THREAD

**Issue by Fatehcis** [nbuytaert1/apex-select2#50]
Very nice and handy plugin, thanks. Is it possible to give it the same look and feel of the native Select List item on APEX UT ?

**Comment by nbuytaert1** [comment]
The latest version of the Select2 APEX plugin includes a new component setting (Shared Components > Component Settings > Select2 [Plug-in]): Look and Feel. Select "Universal Theme" for better (not perfect) UT integration.

**Comment by Fatehcis** [comment]
Hello Nick,
Great. Thanks for your email..


     Fateh Almsaddi, *COO*, M: (+971) 55 667 5271 <+971556675271>
------------------------------
[image: FAM Properties] <http://dubai.famproperties.com/>
Building 13, Office 303 & 304
Bay Square - Business Bay
Burj Khalifa District
P.O Box 215088
Dubai, UAE
*fäm*Properties.com <http://dubai.famproperties.com>
Location Map
<https://www.google.com/maps/place/f%C3%A4m+Properties+-+Dubai+Real+Estate+Brokers/@25.1870084,55.2816753,17z/data=!4m2!3m1!1s0x0000000000000000:0x64b7bc4ca8ecb767?hl=en-US>

*Stay Connected*
[image: Facebook] <https://www.facebook.com/famproperties>   [image:
LinkedIn] <http://www.linkedin.com/in/famproperties>   [image: Twitter]
<https://twitter.com/famproperties12>   [image: Youtube]
<http://www.youtube.com/user/famproperties123>   [image: Blog]
<http://blog.famproperties.com/>   [image: Plus]
<https://plus.google.com/+Famproperties2>

 Please consider the environment before printing this email.
