### ISSUE TITLE
Toggle and ORA-06502

### ISSUE THREAD

**Issue by Mike682** [nbuytaert1/apex-select2#52]
Hi Nick,

First of all, thank you for the grate work you did on this select2 plugin.

I have used it many times and it helps me a lot. But today I am facing this ORA-06502 error when I use the Toggle functions. it works fine if my LOV is having limited returns values, but if the return is too much, I had this Ora-error.

If I use the single-select or multiple-select, the same LOV works fine though.

Thanks..

Mike

ORA-06502: PL/SQL: numeric or value error: character string buffer too small

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -6502
ora_sqlerrm: ORA-06502: PL/SQL: numeric or value error: character string buffer too small
component.type: APEX_APPLICATION_PAGE_ITEMS
component.id: 42028783639183465
component.name: P95_SERVER_LIST
error_backtrace:
ORA-06512: at line 229
ORA-06512: at line 498
ORA-06512: at line 617
ORA-06512: at line 863
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1033
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047
ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 892
ORA-06512: at "APEX_050000.WWV_FLOW_PLUGIN", line 1146

**Comment by nbuytaert1** [comment]
Hey Mike,

Can you explain what this "Toggle fucntion" is? I don't know what you are referring to.
Have you tried enabling lazy loading? That might prevent the ORA-06502 error from occuring.

**Comment by Mike682** [comment]
Hi Nick,

Thank you for the response.

I was talking about the "Tagging Support"(sorry, not the "Toggle"),

Yes I tried the lazy loading but I am still getting the errors.  I was thinking maybe this is because of the 32767 varchar2 limit of Oracle but then the other choose("Multiple-Value list"/"Single-Value List" works fine, so that make me thinking maybe it's not because of the varchar2 limit.

The only reason I prefer Tagging over Multiple-value is because Tagging is allowing me to enter new values which is not in the LOV while Multiple-value is not, and I need to let customer be able to enter new values if they can't find it in the LOV

This only happens if my LOV return lots of values, if I reduce the LOV data volume, it works fine

Thanks again for your help in advance

**Comment by Mike682** [comment]
Hi Nick,

You are right, Turned out setting it to Lazy loading solves the issues

Thanks again for the help!
