### ISSUE TITLE
Kaspersky Antivirus Issue - Freezing Select2 Plugin

### ISSUE THREAD

**Issue by egoncalez** [nbuytaert1/apex-select2#54]
After install Kaspersky Antivirus pages that uses select2 plugin are freezed and navigator crash after some minutes.
What kind of code in the plugin could be responsible for this. I don't see why AV interpret the code as malicious and block it.
I'm using Apex 5.

**Comment by nbuytaert1** [comment]
I actually have no idea. Does this antivirus have some kind of logs? You might find something relevant there.

**Comment by nbuytaert1** [comment]
No further feedback. Closing this issue.
