### ISSUE TITLE
Allow for a custom CSS file

### ISSUE THREAD

**Issue by rimblas** [nbuytaert1/apex-select2#55]
Hi Nick, I enhanced the plugin to allow either Select2, Universal Theme or Custom styling.
However, it looks like the plugin.sql file and the code inside the plugin have lots of differences. Some could be significant (to someone at least).
Would you recommend I start with the code in the plugin export file and overwrite the plugin.sql ?

BTW, the change is fairly simple I think. These will be the new lines:

```
  l_custom_css_file          gt_string := p_plugin.attribute_08;
  l_custom_css_path          gt_string := p_plugin.attribute_09;


  elsif l_look_and_feel = 'CUSTOM' then
    apex_css.add_file(
      p_name      => apex_plugin_util.replace_substitutions(l_custom_css_file),
      p_directory => apex_plugin_util.replace_substitutions(l_custom_css_path),
      p_version   => null
    );
  end if;
```

**Comment by nbuytaert1** [comment]
Hey Jorge,

That's my mistake. I have tried to upgrade the plugin to make use of Select2 4.0.0, but ran into some annoying issues. I did commit some incomplete work, which explains the difference between plugin.sql and the code inside the plugin.

It's fine if you just add your changes to the plugin.sql file. I'll then try to merge your changes whenever I find the time.

Thanks,
Nick

**Comment by nbuytaert1** [comment]
I have added the ability to include a custom CSS file via _Shared Components > Component Settings_. It will be released in the next version of the plugin. Thanks for the feature request.

**Comment by rimblas** [comment]
That's great Nick, thank you!
