### ISSUE TITLE
Issue with Select list that has >> and & in the display

### ISSUE THREAD

**Issue by dnovotny32** [nbuytaert1/apex-select2#64]
Within APEX 5.0.3 - I have a select2 3.0 list that has ">>" values in the list ... when select2 displays them I get &gt;

In the data:
>> IT>>TSG>>IM

Select2 Displays
&gt;&gt;IT&gt;&gt;TSG&gt;&gt;IM

Also:  When I upgraded from 2.4 (?) to 3.0 the style of the select2 changed.  I would like to go back to the previous style (size, font, etc.) but I am not sure where to change it (I am an APEX rookie).

**Comment by mendesn** [comment]
To go back the previous style go to components and edit

Em 03/08/2016 01:14, "dnovotny32" <notifications@github.com> escreveu:

**Comment by dnovotny32** [comment]
Thanks – But the Font Size isn’t like the rest.  Also:  Here is the screen shot of the character issue that I am seeing (it worked in the previous version).  Any ideas on how to fix this?

[cid:image003.jpg@01D1ECE3.85C4BED0]

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by mendesn** [comment]
Try using style="the font you want" in css field properties

Em 03/08/2016 01:30, "dnovotny32" <notifications@github.com> escreveu:

**Comment by dnovotny32** [comment]
Thanks – any idea on the display issue (with the >>)???

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by nbuytaert1** [comment]
Hi David, does the problem occur only when you enable lazy loading?

**Comment by mendesn** [comment]
Can you try and replace by another character? Do you realy need >>?

Em 03/08/2016 18:43, "dnovotny32" <notifications@github.com> escreveu:

**Comment by dnovotny32** [comment]
Kind of … when Lazy Loading is turned off I get >>>> (instead of just 2 ).  Here is the screen shot:

[cid:image003.jpg@01D1ED79.07B01120]


David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by dnovotny32** [comment]
Interesting!!!


-          I replaced all >> with > -- got the same error  (replaced > with &gt;)

-          I replaced all >> with >> and it worked (I also tried \ which worked)

Do you know what the problem is … at least I have a workaround!!

BTW:  thanks for putting this plug-in together … it is such a life saver for our users!

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by dnovotny32** [comment]
Do you think you will be able to get the lazy loading to work with “>>” in the display column?  Not having it really impacts performance of screens coming up.

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

From: Novotny, David W 584
Sent: Wednesday, August 03, 2016 3:19 PM
To: 'nbuytaert1/apex-select2'
Subject: RE: [nbuytaert1/apex-select2] Issue with Select list that has >> and & in the display (#64)

Interesting!!!


-          I replaced all >> with > -- got the same error  (replaced > with &gt;)

-          I replaced all >> with >> and it worked (I also tried \ which worked)

Do you know what the problem is … at least I have a workaround!!

BTW:  thanks for putting this plug-in together … it is such a life saver for our users!

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by nbuytaert1** [comment]
Hi David,

> Do you think you will be able to get the lazy loading to work with “>>” in the display column?  Not having it really impacts performance of screens coming up.

Download and install version 3.0.1 of the plugin to properly display the ">>" characters in combination with lazy loading. Make sure to set the _Escape special characters_ page item setting to _Yes_.

Can you let me know whether that works for you?

Thanks,
Nick

**Comment by dnovotny32** [comment]
Nick,

Thanks a lot for fixing it … it works really well!

I still can’t figure out how to change the font size … I have tried style= in a bunch of the CSS fields.  Can you tell me which field I should be making the change in … and an example of what to put in?  Sorry … I am a newbie when it comes to this stuff.

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by nbuytaert1** [comment]
> I still can’t figure out how to change the font size … I have tried style= in a bunch of the CSS fields.  Can you tell me which field I should be making the change in … and an example of what to put in?  Sorry … I am a newbie when it comes to this stuff.

I'll need a little more info first.
- What APEX version are you on?
- What theme are you using?
- What _Look & Feel_ did you select under _Component Settings_?

**Comment by dnovotny32** [comment]
Apex 5.0.3
Universal Theme - 42
Select2 (Look and Feel)

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by nbuytaert1** [comment]
Sorry for the delay.

I did a quick test on apex.oracle.com, but I noticed nothing abnormal. Here's how my test page looks like: https://apex.oracle.com/pls/apex/f?p=10486:1

Did you include custom CSS code on your pages? It is possible that the custom CSS code overwrites Select2 specific styles.

Can you replicate the font size issue on apex.oracle.com and grant me developer access? That allows me to take a look at the actual problem and come up with a solution.

**Comment by dnovotny32** [comment]
I just looked at your test page … notice how your label font size is different than you drop down font size … I am trying to get them to be close to the same.

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2016 CIGNA

**Comment by nbuytaert1** [comment]
> I just looked at your test page … notice how your label font size is different than you drop down font size … I am trying to get them to be close to the same.

That's actually standard behavior. If you want to change the font size of the drop down items, add the following CSS rule to your page(s).

```css
.select2-container .select2-dropdown .select2-results ul li {
  font-size: 12px;
}
```

**Comment by dnovotny32** [comment]
Nick,

Hey – long time no talk … I still love the SELECT2 plug-in … question for you:  Has select2 been updated (fixed) so that tagging doesn’t allow duplicates – example:

Free
free
frEE

the tag would only allow the first one to be stored so that I don’t end up with 3 different versions.  Does that make sense?

David Novotny
Cigna
ph: 303-566-5665
Confidential, unpublished property of CIGNA. Do not duplicate or distribute. Use and distribution limited solely to authorized personnel. © Copyright 2017 CIGNA

**Comment by nbuytaert1** [comment]
Not yet, but it will be included in the next release.

However, the new release for the Select2 plugin is being blocked because of Interactive Grid support. I still didn't succeed to get IG support fully working...
