### ISSUE TITLE
Null Display Value is cut off

### ISSUE THREAD

**Issue by akanzmeier** [nbuytaert1/apex-select2#65]
When the plugin is set to a multi-value select list, the Null Display Value is cut off.
![select_list_feedback](https://cloud.githubusercontent.com/assets/14890238/17466617/0d2cd1cc-5cd9-11e6-922c-a45e02d4c788.jpg)

**Comment by nbuytaert1** [comment]
I'll have that fixed in the next version of the plugin. For now, as a temporary fix, you can include the following CSS lines on page level to properly display the null display values.

`.select2-selection--multiple .select2-search--inline .select2-search__field {
  width: auto !important;
}`

**Comment by akanzmeier** [comment]
Thanks!!  The solution worked great!
