### ISSUE TITLE
Universal Theme Look and Feel no longer works

### ISSUE THREAD

**Issue by nbuytaert1** [nbuytaert1/apex-select2#66]
Drop the _Universal Theme_ Look and Feel option.

**Comment by turntablez** [comment]
Are you dropping this completely? Thanks

**Comment by nbuytaert1** [comment]
The _Universal Theme_ Look and Feel isn't working anymore since version 3.0.0 of the plugin. The HTML structure of the Select2 items has changed completely, and thus breaking the custom-written CSS code for the UT style. If I fix the CSS code this time, I'm pretty sure it will break again by future changes to Select2 and/or Universal Theme.

So I'd have to put quite some time in an easy-to-break feature, of which I think the result wasn't that great. That sounds bad, right? ^^

On the other hand, maybe it's easy to change the existing CSS code and make it work for v3.0.0. In that case, I might be able to keep this feature alive. I'll take a closer a look at the HTML and CSS code as soon as I find some time.
