### ISSUE TITLE
Ability to list all values into the select list that partially match the characters- Enhancement 

### ISSUE THREAD

**Issue by brinal-dm** [nbuytaert1/apex-select2#67]
Hi, 

I want to list all options that matches the search term partially. For eg: If search term is "st hn", it should list all options that consists of st hn characters. Basically substitute space with like operator.

So far I have done below:
Created a dynamic action which makes ajax call on select list as below:
This makes calls to database procedure and return json data, Although the problem with this is that the database procedure fails if the search term matches and returns more data.  

$("#P5_SELECT2").select2({
  minimumInputLength: 2,  
 ajax: {
   type:"POST",  
  url:"/apex/item_search",
   data: function (params) {
     return {
        p_search_term: encodeURIComponent(params.term), // search term
      };
},
mimeType:"application/json",
processResults: function(data, params)
{
var select2Data = $.map(data,function(obj){
    obj.id = obj.id;
    obj.text = obj.segment;
    return obj;
});
 return {
         results: select2Data 
      };
cache: true
},
error: function(xhr,error){ 
    console.debug(xhr);
    console.log(error);
}
}

});
//});

database procedure:

CREATE OR REPLACE PROCEDURE item_search(p_search_term IN VARCHAR2) IS
 l_cursor  SYS_REFCURSOR;
 l_inventory_item_id Number;
 l_data clob;
 l_data1 clob;
 l_cnt NUMBER := 1;
 BEGIN
   l_data  := EMPTY_CLOB();
        DBMS_LOB.CREATETEMPORARY(l_data,TRUE,10); 
        DBMS_LOB.CREATETEMPORARY(l_data1,TRUE,10);   

```
for rec in (select '{"id":'||inventory_item_id||',"segment":"'||segment1 || ' ' || substr(DBMS_XMLGEN.CONVERT(description), 1, 30)||'"}' json_string from mtl_system_items_b
    where organization_id = 84
    and lower(inventory_item_status_code) = 'active'
    and (lower(segment1) like '%'||lower(p_search_term)||'%' OR lower(description) like '%'||lower(p_search_term)||'%')
    order by (DECODE(p_search_term||'%',segment1||'%',0,1)),segment1 asc
    )
```

   loop
      IF l_cnt =1 THEN

```
     dbms_lob.append(l_data, rec.json_string);

   ELSE
     dbms_lob.append(l_data,','||rec.json_string);
   END IF;  

    dbms_lob.append(l_data1,l_data);
    l_data  := EMPTY_CLOB();
    DBMS_LOB.CREATETEMPORARY(l_data,TRUE,10);  

    l_cnt := l_cnt +1;        
```

   end loop;    

   htp.p('['||l_data1||']');

```
dbms_lob.freetemporary(l_data); 
dbms_lob.freetemporary(l_data1); 
EXCEPTION WHEN OTHERS THEN
 htp.p('error is'||SQLERRM);
```

   END;   

Any help is greatly appreciated.

**Comment by nbuytaert1** [comment]
I'll see if I can update the plugin to allow support for this kind of search algorithm. I'll keep you posted on the progress.

**Comment by brinal-dm** [comment]
Thanks Nick for making time to look at this enhancement.

**Comment by nbuytaert1** [comment]
I have found a way to support the new search algorithm. I'll release a new version of the plugin in one of the next days.

Am I right that you're using version 2.4.3 of the Select2 APEX plugin? If so, will you be able to upgrade to the latest version of the plugin?

**Comment by nbuytaert1** [comment]
I released version 3.0.2 of the Select2 APEX plugin. It includes a new _Search Logic_ option: _Multi-word Search_. This search algorithm should fit your requirements.

**Comment by brinal-dm** [comment]
Hey Nick,

First of all thanks a lot for new version. Sorry for the delay in replying to your comment, yes I am on version 2.4.3. Yes I am going to upgrade right now and will let you know about the results.

**Comment by brinal-dm** [comment]
Hey Nick,

Worked really well, Also performance is good. Thanks for the new version.

**Comment by nbuytaert1** [comment]
Okay. Thanks for the feedback.
I'll close this issue now.

**Comment by brinal-dm** [comment]
Hi Nick,

Is there a way that I can list the option that matched with my search term first in drop down list or say rather arrange the values in drop down list in order that I enter in my search term? 

For eg: search term = 'hnwe 34' and LOV consists of 
1. hnwe 34 stan for rl
2. 123233 hnwe test
3. hnwe 34 best  

Then list the drop down value starting with hnwe 34 first and all the other options later on.  So in this case the order will alphabetical based on search term like below:
hnwe 34 best
hnwe 34 stan for rl
123233 hnwe test 

Is it something I can do easily or needs to update plugin?
