### ISSUE TITLE
Select2 V3 doesn't work on modal pages in Apex5.1

### ISSUE THREAD

**Issue by sokosp** [nbuytaert1/apex-select2#72]
Hi Nick
again great work and thanks for your efforts.
We tried to use your new Select2 on our Apex5.1 app we are testing, but for some reason, on modal pages, it won't let you type anything in the search box. Have you seen similar behaviour?

![clipboard012](https://cloud.githubusercontent.com/assets/21083416/22025236/8f90c9ee-dcd5-11e6-97f4-93d7d9997b2c.jpg)

(Select 2.6.4 worked well, but it didn't work inside Interactive Grid that Apex 5.1 introduced, that's why we tested your newer version.)

**Comment by sokosp** [comment]
Hi Nick,
I made a page for you here to test it (public page) on Oracle apex.

https://apex.oracle.com/pls/apex/f?p=58302:22

As you can see on the page the Select2 you can type and search.
On the modal, same Select2 doesn't let you type.
I m surprised nobody else has noticed this, did you see it?

**Comment by nbuytaert1** [comment]
Thanks for the bug notification.

I believe this problem is only occurring when you're using a Select2 page item inside an **inline dialog** region. Select2 items inside modal dialog pages do not experience this problem. Can you confirm this?

I'll have to add an extra option to the Select2 plugin initialization to fix this: _dropdownParent_.
https://select2.github.io/options.html#dropdownParent

I'll be able to fix this in one of the upcoming days. I first need access to an APEX 4.2 environment.

**Comment by sokosp** [comment]
Yes that is correct, inside an inline dialog region (modal)
do you need a 4.2 installation? i can prepare a VM for you if you want, let me know.

**Comment by nbuytaert1** [comment]
Thanks for the offer, but that's not necessary.
I have some issues with my 4.2 environment right now. I hope it will be fixed by tomorrow.

**Comment by nbuytaert1** [comment]
I released version 3.0.3 of the Select2 APEX plugin, which includes an _Extra Options_ attribute. This new attribute lets you add any arbitrary Select2 jQuery plugin options. Add the following line for Select2 page items that are part of an _Inline Dialog_ region:

`dropdownParent: $('.ui-dialog')`

That should fix the search box issue.

**Comment by sokosp** [comment]
Thank you Nick,
Where do you add this code: dropdownParent: $('.ui-dialog') ?

(sorry i m not very experienced with js/scripts apart from Apex developing)

**Comment by nbuytaert1** [comment]
> Where do you add this code: dropdownParent: $('.ui-dialog') ?

Copy and paste `dropdownParent: $('.ui-dialog')` in the new Extra Options item plugin attribute.

![image](https://cloud.githubusercontent.com/assets/4996854/22293533/46ab7404-e310-11e6-940f-500f9ef78b5e.png)

**Comment by sokosp** [comment]
Thanks monsieur! 

Now it has another problem, SELECT2 doesn't start searching when users enter letters in capitals.
Works only with small letters.
I m trying to re-create it and make a report for you.
Any idea?

**Comment by nbuytaert1** [comment]
What _Search Logic_ option did you select for your Select2 page item? _Contains & Ignore Case_ is the default value and should let you search in a case-insensitive manner.
