### ISSUE TITLE
issue at multiple values load

### ISSUE THREAD

**Issue by AdvenD** [nbuytaert1/apex-select2#76]
I try everything but without success.
I separate value with colon to the page item (e.g. 7839:7521) but nothing at all. If there are more than one value,it show nothing. If there only one,it show  the first value.
I work on 5.1

**Comment by nbuytaert1** [comment]
Are you setting the value client or server side? You can set multiple values using JavaScript like this:

`apex.jQuery("#P10_MY_ITEM").val(["7839","7521"]).trigger("change");`

Or you can use a default value for the page item. In that case, you just have to enter _7839:7521_ as a static value.

**Comment by AdvenD** [comment]
Goodmorning,
I load the values from the server side. It works with static values but thats not our target. The jquery code is a step forward. Now i must try to make this work with apex item array.

Thanks,
any further help will appreciate,
Jamew

**Comment by nbuytaert1** [comment]
Can you reproduce your issue on apex.oracle.com and grant me workspace access? That's the easiest way for me to help you further.

**Comment by AdvenD** [comment]
To be honest and not be annoying, you gave me some solution to  solve my problem Nick, so close the issue.   To be more specific, now i must try to give value from a apex text field with array(1234:1232:1242),which load values from table. 

By the way you gave us a lot of fuctionality with your plugins. Keep the good work.

**Comment by nbuytaert1** [comment]
Use a hidden item on your page that contains the values (for example: 16:15:117). Then you can use the JavaScript split function to transform the values into an array:

`apex.jQuery("#P10_MY_ITEM").val($v("P10_HIDDEN_ITEM").split(':')).trigger("change");`

**Comment by AdvenD** [comment]
Solved. Thank you very much!!!
