### ISSUE TITLE
Setting Item Value from PL/SQL

### ISSUE THREAD

**Issue by pettinger** [nbuytaert1/apex-select2#77]
Hi,
i have an issue when setting the ITEM Value out of an PL/SQL Procedure using       APEX_UTIL.SET_SESSION_STATE('P35_ARBEITSPLATZGRUPPE',coalesce(rTmpStechung.STNRMASCH, rTmpStechung)).
The value is shown in session state of the item, but the lov does not select the according row. it stays empty. but as soon as you drop down the list, the correct row is selected.
![select2](https://cloud.githubusercontent.com/assets/20111123/23856796/2a847f68-07fb-11e7-9d2c-09e8baf57e7c.gif)

as soon as i switch the item type from select2(plugin) to the standard Select List, setting the item works like charm.
any clue what might go wrong ?

regards 
peter

**Comment by nbuytaert1** [comment]
Hi Peter,

Are you executing `APEX_UTIL.SET_SESSION_STATE` as part of a PL/SQL dynamic action? In that case, you'll have to add an _Execute JavaScript Code_ action after the _Execute PL/SQL Code_ action. Add the following JavaScript code to actually set the item's value in the Select2 item.

```javascript
$("#P35_ARBEITSPLATZGRUPPE").trigger("change");
```

Also, it looks like you are using an old version of the Select2 APEX plugin. Is it possible for you to upgrade to the latest version (3.0.3)? There's a higher chance of bugs in old versions of the plugin.

Hope that helps,
Nick

**Comment by pettinger** [comment]
Thanks for the reply.
Adding the Javascript action did the trick. But to make it work, i had to change the "wait for result" property of the pl/sql action to "yes". took me some time to figure that one out.

Peter
