### ISSUE TITLE
Wrong content type of lazy loading response

### ISSUE THREAD

**Issue by oklimberg** [nbuytaert1/apex-select2#79]
Hi, 

when using this plugin with lazy loading enabled, the response of the AJAX call has the content type
`Content-Type: text/html;charset=UTF-8` instead of `Content-Type: application/json`.
Is there a way to change this?

**Comment by nbuytaert1** [comment]
Hello,

Thanks for the pull request.
I'll merge it with the next release of the plugin.

Nick
