### ISSUE TITLE
When using Select2 in an interactive grid in single selection mode, selection jumps to the lower left corner when typing in search bar

### ISSUE THREAD

**Issue by mfreu** [nbuytaert1/apex-select2#82]
Hi, 

When using Select2 in an interactive grid (Apex 5.1) in single selection mode, selection jumps to the lower left corner when typing in search bar. 

As mentioned this only happens when using the single selection mode.

Maybe there is a quick workaround?

Cheers,
Mirko

**Comment by farzadso** [comment]
I haven't tested select2 on IG, does it render correctly?

**Comment by mfreu** [comment]
Yes it does. But as I said, the select list jumps to to lower left Corner, when typing in the search bar.

**Comment by advancedits** [comment]
I'm having same issue as @mfreu , when you start typing so it can auto suggest, the select list jumps to the bottom left

**Comment by advancedits** [comment]
I guess this is still an open issue #73 

Here's a screenshot on how it looks when you type in the search bar using the sample application
https://apex.oracle.com/pls/apex/f?p=47839:1:104354115372550:::::


<img width="1339" alt="screen shot 2017-05-24 at 5 53 49 pm" src="https://cloud.githubusercontent.com/assets/11402621/26431523/4f3c46fa-40aa-11e7-9af4-29d59c9b01de.png">

**Comment by tuanphat1303** [comment]
Please help me , I've got same issue . Any suggest or fix for this ? :'(

**Comment by Ora-solution** [comment]
Hi Nick,
I'm facing same issue. Your cooperation in this regard will be highly appreciated.

**Comment by nbuytaert1** [comment]
I'm getting close to a 100% working solution. I'll release a new version of the plugin by the end of the week.

I'm going to close this issue now since it's a duplicate. You can subscribe to issue #73 for further updates.
