### ISSUE TITLE
Required property is not used in plugin

### ISSUE THREAD

**Issue by APEXGru** [nbuytaert1/apex-select2#85]
The new "Value Required" property is used to create the HTML 5 required attribute on a regular APEX element. The Select2 plugin needs to respect that setting as well (thus throw in an additional "required" attribute).

**Comment by nbuytaert1** [comment]
Thanks for the remark. I added the following IF condition:

```sql
if p_item.is_required then
  htp.p(' required aria-required="true"');
end if;
```

This issue will be included in release 3.1.0.
