### ISSUE TITLE
Lazy-loading: small change suggestion for a big performance gain

### ISSUE THREAD

**Issue by 77capr** [nbuytaert1/apex-select2#86]
I am looking up names in a 150'000 persons directory using lazy loading. My page load went from several seconds to instantaneous through this modification:
Around line 78 of the 3.0 PL/SQL where it reads:
  `l_lov := apex_plugin_util.get_data`
it reads all the data into memory even though in the lazy-load case it never uses it. So, move that call to line 122 inside the
  `if l_lazy_loading is null`
and it will only be executed when needed. I only tested the change for my use case, but for me it made all the difference.

**Comment by rimblas** [comment]
Ah, very nice find!

**Comment by farzadso** [comment]
@77capr why don't you create a pull request for nick to merge?

**Comment by 77capr** [comment]
@farzadso OK, created my first ever pull request, hope I did it right

**Comment by farzadso** [comment]
@77capr nice! checked it out. Let's see if Nick decides to merge it

**Comment by onlygecko** [comment]
@77capr : You answered the question I was going to ask with an implementation suggestion.  Thanks. :-)

@nbuytaert1 : Can You estimate if and when the commit request will be merged and a new version will be released?

**Comment by nbuytaert1** [comment]
@77capr: Thanks for the pull request. I'll try to merge it this evening.

@onlygecko: I'll release a new version of the plugin this weekend.

**Comment by nbuytaert1** [comment]
@77capr: I merged your pull request. It will be released in version 3.1.0.

Thanks again for creating the pull request.

**Comment by p3t3r** [comment]
Is this code in the plugin plsql? 
I see the change in the source code, but looking at the source of the plugin in APEX, this change is not there.
I'm having issues with performance although lazy loading is set to "Yes".
