### ISSUE TITLE
Add or Select ?

### ISSUE THREAD

**Issue by JacoFourie** [nbuytaert1/apex-select2#98]
Hi.

I see on the sample page you can set the plugin to act as a combobox where you can select a value from the list or add a new one by typing the value. How do you set-up the plugin to do that ?

**Comment by nbuytaert1** [comment]
Change the "Select List Type" setting to "Tagging Support" on your page item.

"When tagging support is enabled, the user can select from pre-existing options or create new options on the fly."

![image](https://user-images.githubusercontent.com/4996854/39561749-ee7cb2d4-4ea7-11e8-9bea-db733ae7cb9f.png)

**Comment by JacoFourie** [comment]
Hi. Thanks for the feedback. I am looking for a Combobox. I can not understand why Apex does not have one out of the box. If I change it to Tagging then I can select more than one from the list or add more than one. The user needs to pick one item or enter a new one. But one item only. Can this plugin do that ? Kind Regards.

**Comment by JacoFourie** [comment]
Aaaa OK You need to make the selection size 1. Thanks for this super cool plugin.
